batch_size: 16
epochs: 200
epochs_til_checkpoint: 50
expand: -1
experiment_name: liver
hidden_num: 256
latent_dim: 128
latent_template_dim: 128
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 5.0
loss_grad_temp: 100.0
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 3000
on_surface_points: 4000
point_cloud_path: $YOUR_SURFACE_POINTS_FILE_HERE$
pretrain_path: $YOUR_PRETRAINED_PATH_HERE$
steps_til_summary: 100